export const MAIN_CARD_CODES = [
  'MAIN_CARD_CRUISING',
  'MAIN_CARD_SPEED_CONTROL',
  'MAIN_CARD_THRESHOLD',
  'MAIN_CARD_NO_BUDGET',
  'MAIN_CARD_DEFAULT',
] as const

export const MAIN_CARD_THRESHOLDS = {
  THRESHOLD_80: 80,
  THRESHOLD_90: 90,
  THRESHOLD_100: 100,
  CRUISING_GAP: 10,
} as const
